## Assignment 1: Working with NumPy

Objective: Understand NumPy basics, array creation, manipulation, and operations.

In [1]:
import numpy as np

### 1. 1D Array Operations

In [2]:
array_1d = np.arange(1, 21)

np.sum(array_1d), np.mean(array_1d), np.median(array_1d), np.std(array_1d), np.where(array_1d > 10)

(np.int64(210),
 np.float64(10.5),
 np.float64(10.5),
 np.float64(5.766281297335398),
 (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),))

### 2. 2D Array Operations

In [3]:
array_2d = np.arange(1, 17).reshape(4, 4)
array_2d, array_2d.T, np.sum(array_2d, axis=1), np.sum(array_2d, axis=0)

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]]),
 array([10, 26, 42, 58]),
 array([28, 32, 36, 40]))

### 3. Random Arrays

In [4]:
a = np.random.randint(1, 21, (3, 3))
b = np.random.randint(1, 21, (3, 3))

a, b, a+b, a-b, a*b, np.dot(a, b)

(array([[ 5, 11, 14],
        [16,  9,  1],
        [ 7, 12, 12]]),
 array([[ 1, 13, 12],
        [15, 18,  5],
        [14, 19,  4]]),
 array([[ 6, 24, 26],
        [31, 27,  6],
        [21, 31, 16]]),
 array([[ 4, -2,  2],
        [ 1, -9, -4],
        [-7, -7,  8]]),
 array([[  5, 143, 168],
        [240, 162,   5],
        [ 98, 228,  48]]),
 array([[366, 529, 171],
        [165, 389, 241],
        [355, 535, 192]]))

### 4. Reshaping and Slicing

In [5]:
arr = np.arange(1, 13).reshape(3, 4)
arr, arr[:2, -2:]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[3, 4],
        [7, 8]]))